#!/usr/bin/env python3

import sys
import shutil
import os
from os.path import exists

if (len(sys.argv) != 3):
    print("Wrong number of args")
    sys.exit(1)

prog = sys.argv[1]
argsfile = sys.argv[2]

if (not shutil.which(prog)):
    print("Executable not found")
    exit(1)

if (not exists(argsfile)):
    print("Input file doesn't exist")
    exit(1)

with open(argsfile, "r") as file:
    args = file.read()

print("Running [{}] on input [{}]".format(prog, argsfile))

os.system(prog + " " + args)
