# theme = "vim_dark_high_contrast"
# theme = "github_dark_high_contrast"
# theme = "everforest_dark"
theme = "github_dark_dimmed"
# theme = "acme"
# theme = "jellybeans"
# theme = "molokai"

[keys.insert]
k = { j = "normal_mode" }

[keys.normal]
"ret" = "goto_word"

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"

[editor]
cursorline = true
lsp.display-inlay-hints = true


[editor.inline-diagnostics]
cursor-line = "hint"

[editor.soft-wrap]
enable = true
