theme = "everforest_dark"

[keys.insert]
k = { j = "normal_mode" }

[keys.normal]
"ret" = "goto_word"

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"

[editor]
cursorline = true
lsp.display-inlay-hints = true


[editor.inline-diagnostics]
cursor-line = "hint"
